id: ACED4C492
title: 'The Method of Accomplishment of Ārya Avalokiteśvara: The Practice of Great
  Compassion & Mahāmudrā in Union'
type: translation
pechas:
- I911F9267
- I88C1C827
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:31:39.495233
  last_modified_at: 2023-01-04 11:31:39.495244
  collections:
  - Chögyal Pakpa Lodrö Gyaltsen
  - Works of Tibetan Masters
alignment_to_base:
  I911F9267/43C1: D998
  I88C1C827/B4A3: D998
